### ISSUE TITLE
prune options doesn't works

### ISSUE THREAD

**Issue by bitchecker** [dusanx/saf#1]
Hi,
I found this project very useful, I'm trying to perform some test, but I think that something is not working with prune options.

In my `.sar.conf` file, I have:
```bash
keep-hourly = 1
keep-daily = 7
keep-weekly = 4
keep-monthly = 12
keep-yearly = 5
```

when I run, `sar backup` I see:

```bash
Prune in src/.saf.conf, [TEST] ==> dst

Backup in src/.saf.conf, [TEST] ==> dst

created directory dst/in-progress
```

In `dst` folder I see a lot of subdirectories, but from config point of view, I should found only one for the specific hour. This is what I see in `dst` folder:
```bash
2023-08-19-134552  2023-08-19-144911  2023-08-19-145208  2023-08-19-145233  2023-08-19-145258  2023-08-19-145316  2023-08-19-145325  2023-08-19-145335  2023-08-19-145458  2023-08-19-145540
2023-08-19-134615  2023-08-19-145019  2023-08-19-145226  2023-08-19-145235  2023-08-19-145300  2023-08-19-145317  2023-08-19-145327  2023-08-19-145339  2023-08-19-145530  2023-08-19-145542
2023-08-19-134643  2023-08-19-145203  2023-08-19-145227  2023-08-19-145236  2023-08-19-145302  2023-08-19-145319  2023-08-19-145329  2023-08-19-145343  2023-08-19-145533  2023-08-19-145545
2023-08-19-134648  2023-08-19-145205  2023-08-19-145228  2023-08-19-145240  2023-08-19-145304  2023-08-19-145321  2023-08-19-145331  2023-08-19-145346  2023-08-19-145536  backup.marker
2023-08-19-144804  2023-08-19-145206  2023-08-19-145229  2023-08-19-145250  2023-08-19-145306  2023-08-19-145323  2023-08-19-145333  2023-08-19-145455  2023-08-19-145538
```

Am I running something wrong?

**Comment by dusanx** [comment]
```
keep-hourly = 1
keep-daily = 7
keep-weekly = 4
keep-monthly = 12
keep-yearly = 5
```
Please note that all the parameters are in days, so keep-weekly , keep-monthly, and  keep-yearly  should be in days too. All the backups listed above seem to done be within one hour, so no prune could kick in.

It would be smart to add additional check that lower prune criteria doesn't contain period in days lower than higher prune criteria (meaning that keep-monthly value is always lower than keep-yearly and so on), so I'll add that soon.

In your example, since everything is in days, criteria should be something like
```
keep-hourly = 1
keep-daily = 7
keep-weekly = 30
keep-monthly = 365
keep-yearly = 1825
```
but each criteria to prune anything would require that backup folder name (date) falls behind date period.

**Comment by dusanx** [comment]
```
keep-hourly = 1 (meaning keep everything for 1 day)
keep-daily = 7 (meaning keep daily backups for 7 days, one for each day)
keep-weekly = 30 (meaning keep weekly backups for 30 days, one for each week)
keep-monthly = 365 (meaning keep monthly backups for a year, one for each month)
keep-yearly = 1825 (meaning keep yearly backups for 5 years, one for each year)
```

**Comment by dusanx** [comment]
I just added sanity check for prune criteria, which will stop with error if any keep-* value is below minimal value that makes sense or if values overlap. Please pull and try.

I'll close this issue but feel free to reopen it if it is not clear.

**Comment by bitchecker** [comment]
Hi,
thanks for fast reply :)

So `keep-hourly` is always related to DAYS, right?

I think that this created confusion, because I was referring to “keep” parameters like borg/restic systems.

**Comment by dusanx** [comment]
Yes, sorry, all keep-* parameters are in days, I'll improve documentation.

**Comment by dusanx** [comment]
Also,` keep-hourly` is bit misleading since it actually means 'keep all', but since most backups of this kind run hourly in cron or similar, from one angle 'hourly' is the correct term.

**Comment by bitchecker** [comment]
I think that it should be considered as a simple number, instead of "days" and use that number to refer to the right unit like:
* `keep-hourly`   -> number of hourly archives to keep
* `keep-daily`    -> number of daily archives to keep
* `keep-weekly`   -> number of weekly archives to keep
* `keep-monthly`  -> number of monthly archives to keep
* `keep-yearly`   -> number of yearly archives to keep

like [borgbackup](https://github.com/borgbackup/borg)/[restic](https://github.com/restic/restic)

They're using the same parameters (and this is why is a little bit confusing on this)

**Comment by dusanx** [comment]
saf backups are not making any difference between daily, weekly, or monthly, they all have the same format for folder names that keep date and time of creation. Same backup you created today will be day old in a day, week old in a week and so on, this way falling into one of the brackets for prune logic. Please see `saf list` output, or rather check it in couple of days, it will be clearer then. Since you can create ten backups in ten minutes, if you specify number of backups to keep that would prune all the others which is a bad idea.

If you have regular hourly backup (remember backup is backup, it will slide down the time but there is no such thing as 'monthly' backup), and want to keep about 50 of them, isn't that similar to specifying 2 days before purging hourly?

Give it few days to see how backups slide back in time (use `saf list` often) then it will make all the sense.

**Comment by bitchecker** [comment]
>  you can create ten backups in ten minutes, if you specify number of backups to keep that would prune all the others which is a bad idea.

Really, this is the idea! Every backup system works like this, and it's correct that if you specify `keep-hourly = 1` and you run 10 backup in that 60 min, it will leave only the latest. It's the expected behavior.

> If you have regular hourly backup (remember backup is backup, it will slide down the time but there is no such thing as 'monthly' backup), and want to keep about 50 of them, isn't that similar to specifying 2 days before purging hourly?

Yes, at the end is the same, but it's tricky if all around the world the standard works in another way.

> Give it few days to see how backups slide back in time (use `saf list` often) then it will make all the sense.

Ok, but the main issue starts with “hourly” parameter…as I said, if I run 10 times a backup in an hour and I have all the versions in my destination.
The day after, when you push a new backup, the prune process will keep all the 10 backups for 7 days. This is not correct because you want to keep “one daily backup only” (also if you executed it several times, for testing it for example)

**Comment by dusanx** [comment]
Sorry, no, that's the wrong way and not the industry standard. If you create 10 backups in 10 minutes that's because you are experimenting or want to keep something between changes, and that definitely should not kill previous backups.

Industry standard goes the both ways at best, for backups that differentiate daily/weekly/monthly it may make sense, for backups that don't (and there is lots of them) if you make multiple quick backups you want to keep them, or wait for prune to pick them up after some days, or manually delete them.

Backups are hardlinked and taking very little space anyway, see `saf realsizes`.

**Comment by dusanx** [comment]
As a illustration:

https://github.com/laurent22/rsync-time-backup#backup-expiration-logic

**Comment by bitchecker** [comment]
I completely agree with the space efficiency, but I can link also documentation that explain what I want to tell:
* https://borgbackup.readthedocs.io/en/stable/usage/prune.html
* https://restic.readthedocs.io/en/stable/060_forget.html#removing-snapshots-according-to-a-policy

for sure, `you need to be careful, prune is a potentially dangerous command, it will remove backup archives.`

For sure, if you don't want to remove, you'll set up the right parameter for your setup, but this can't be the “general case” IMHO.

**Comment by dusanx** [comment]
I understand the logic but most or all of the Apple time machine like programs, including Apple time machine, follow the logic of sliding backups that got pruned with time difference. Borg is completely different snapshot tool, I use it too, but its logic is not fully applicable to rsync-based or harlinked backups. I could link tens of tools more similar to saf that follow the date expiration logic.

I still think that you need to see `saf list` in a few days, preferably in a month. There is no such concept as daily/hourly/weekly/monthly/yearly backups in saf. Each backup is any of them if enough time passes.

**Comment by bitchecker** [comment]
> I still think that you need to see `saf list` in a few days, preferably in a month. There is no such concept as daily/hourly/weekly/monthly/yearly backups in saf. Each backup is any of them if enough time passes.

I think that we're confusing using “time based retention policy parameters” like “number based retention policy”

Also new checks that you added in the latest commit, are forcing a policy that you're considering right, but users don't.
e.g. 

_I want to keep only the latest backup on a hetzner storage box because i don't want to version on cloud system, but I want to keep only the “live data”._

This is not possible at the moment (`.saf.conf [T1] error: keep-weekly must be at least 7 days`), and I think that a tool should act as the user prefer and not like the programmer wants.

**Comment by dusanx** [comment]
> I want to keep only the latest backup on a hetzner storage box because i don't want to version on cloud system, but I want to keep only the “live data”.

You don't need any backup solution for this, create one line script that rsync-s your data to single folder on Hetzner? Rsync with `--delete` flag to single location is exactly what you need to cover that case.

**Comment by bitchecker** [comment]
Really?
So you created a tool for what? Do only what you want that people should do?

About my example, and not only, I really don't need your tool, I have a big choice and a lot of solutions already in place… I like the idea to have a configuration file for rsync and the possibility to version, and I was giving a try…but really no new stuff under the sun. So, if for you, suggestions are not useful… I wish you all the best with your development. :+1:

**Comment by dusanx** [comment]
Sigh. There is nothing to fix for anybody that needs proper backup and not a toy. Significant time spent trying to reasonably explain rationale is wasted. Oh well.
