### ISSUE TITLE
backup.marker file manual creation

### ISSUE THREAD

**Issue by bitchecker** [dusanx/saf#2]
Hi,
I see in your documentation `[...] In short just follow instructions when backup.marker related message appears.`

Why this necessary file is not automatically created?

**Comment by dusanx** [comment]
Could be automatic but that would defy the purpose of backup.marker, which is to make sure that we have proper access to the destination. For instance, I could define /mnt/disk-I-have/path/that/doesnt/exists. Manual path and marker creation make sure that user checks once more if the path is correct, while marker just serves as a quick check if we can reach it (on each command). 

Since this is one time operation it didn't seem like too demanding to request separate step, but if it proves to be a burden no problem to think about some automation. Current logic, if path and marker file don't exist at the destination, is to ask user to execute both commands in shell, so if anything goes wrong with the connection parameters we have cleaner problem report.

I'll leave this open for now to see what other users think.

**Comment by dusanx** [comment]
I'll temporarily close this issue as 'not planned' but please anybody feel free to discuss.
